services:
  servidor:
    build: 
      context: .
      dockerfile: ./cmd/servidor/Dockerfile
    container_name: servidor-ct
    ports:
      - "5000:5000" #http://localhost:5000
    volumes:
      - ./internal/dataJson/regiao.json:/app/internal/dataJson/regiao.json
      - ./internal/dataJson/veiculo.json:/app/internal/dataJson/veiculo.json
    networks:
      - recarga-inteligente-net

  veiculo:
    build: 
      context: .
      dockerfile: ./cmd/veiculo/Dockerfile
    container_name: veiculo-ct
    depends_on:
      - servidor
    stdin_open: true
    tty: true
    networks:
      - recarga-inteligente-net
    environment:
      - SERVER_ADDRESS=servidor
      - SERVER_PORT=5000

  ponto-de-recarga:
    build: 
      context: .
      dockerfile: ./cmd/ponto-de-recarga/Dockerfile
    container_name: ponto-de-recarga-ct
    depends_on:
      - servidor
    stdin_open: true
    tty: true
    networks:
      - recarga-inteligente-net
    environment:
      - SERVER_ADDRESS=servidor
      - SERVER_PORT=5000

networks:
  recarga-inteligente-net:
    driver: bridge
