services:
  servidor:
    build: .
    command: /app/servidor
    ports:
      - "5000:5000" #http://localhost:5000
    networks:
      - recarga-inteligente-net

  veiculo:
    build: .
    command: /app/veiculo
    depends_on:
      - servidor
    networks:
      - recarga-inteligente-net
    environment:
      - SERVIDOR_ADDR=servidor:5000
    deploy:
      replicas: 6


  ponto-de-recarga:
    build: .
    command: /app/ponto-de-recarga
    depends_on:
      - servidor
    networks:
      - recarga-inteligente-net
    environment:
      - SERVIDOR_ADDR=servidor:5000
    deploy:
      replicas: 3

networks:
  recarga-inteligente-net:
    driver: bridge
