version: '3.8'

services:
  servidor:
    build: ./servidor
    container_name: servidor
    ports:
      - "5000:5000" #http://localhost:5000
    networks:
      - recarga-inteligente-net

  veiculo:
    build: ./veiculo
    container_name: veiculo
    ports:
      -5001:5000 #http://localhost:5001
    depends_on:
      - servidor
    networks:
      - recarga-inteligente-net
  
  ponto-de-recarga:
    build: ./ponto-de-recarga
    container_name: ponto-de-recarga
    ports:
      -5002:5000 #http://localhost:5002
    depends_on:
      - servidor
    networks:
      - recarga-inteligente-net

networks:
  recarga-inteligente-net:
    driver: bridge
